### ISSUE TITLE
Logs can't be placed horizontally.

### ISSUE THREAD

**Issue by Hazorux** [Fellteros/vanillablocksplus-1.20.1#1]
After installing the mod, logs of any kind will always be placed upright.
Tested with "vanillablocksplus-2.0.4.jar" on fresh install of Minecraft version 1.21.1 with fabric loader 0.16.5 downloaded from modrinth via ATLauncher.

I get a few yellow warnings in the console, when launching the game:

> [15/09/2024 02:33:43 AM] [Worker-Main-12/WARN] Texture vanillablocksplus:item/vbp_title with size 1028x1028 limits mip level from 4 to 2
> [15/09/2024 02:33:43 AM] [Worker-Main-12/WARN] minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 2, because of minimum power of two: 4
> [15/09/2024 02:33:45 AM] [Worker-Main-7/WARN] Exception loading blockstate definition: 'vanillablocksplus:blockstates/leaves_def.json' missing model for variant: 'vanillablocksplus:leaves_def#'
> [15/09/2024 02:33:45 AM] [Worker-Main-7/WARN] Exception loading blockstate definition: 'vanillablocksplus:blockstates/log_def.json' missing model for variant: 'vanillablocksplus:log_def#'
> [15/09/2024 02:33:45 AM] [Worker-Main-7/WARN] Exception loading blockstate definition: 'vanillablocksplus:blockstates/nether_def.json' missing model for variant: 'vanillablocksplus:nether_def#'
> [15/09/2024 02:33:45 AM] [Worker-Main-7/WARN] Unable to load model: 'vanillablocksplus:item/nether_def' referenced from: vanillablocksplus:item/nether_def: java.io.FileNotFoundException: vanillablocksplus:models/item/nether_def.json
> [15/09/2024 02:33:45 AM] [Worker-Main-7/WARN] Unable to load model: 'vanillablocksplus:item/log_def' referenced from: vanillablocksplus:item/log_def: java.io.FileNotFoundException: vanillablocksplus:models/item/log_def.json
> [15/09/2024 02:33:45 AM] [Worker-Main-7/WARN] Unable to load model: 'vanillablocksplus:item/leaves_def' referenced from: vanillablocksplus:item/leaves_def: java.io.FileNotFoundException: vanillablocksplus:models/item/leaves_def.json

**Comment by Fellteros** [comment]
log placement will be fixed in 2.0.5, those warns are template blocks without any texture or blockstates since you can't use `AbstrackBlock.Settings.Copy()` on logs without getting an error. thx for pointing this out
