### ISSUE TITLE
using Vanilla+blocks glazed terracotta not oriented correctly

### ISSUE THREAD

**Issue by sasquott** [Fellteros/vanillablocksplus-1.20.1#4]
without the mod, continuity is handling the patterns on glazed terracotta corectly, with Vanilla _ Blocks added, the blocks do not change orientation, are always fixed facing a set single direction, so the joined patterns are broken.
![glazed_broke](https://github.com/user-attachments/assets/edb160e4-4e80-40b0-9af5-3cb4298fb3fa)

how they should look
![glazed_correct](https://github.com/user-attachments/assets/221f1776-c42a-4f59-ab5d-511504efb6be)

Minecraft 1.21.1 using latest release 2.0.5 on fabric, iris, sodium & continuity -   issue still there with shaders off

**Comment by Fellteros** [comment]
Hi,
when generating blockstates and models, the vanilla method generates a singleton blockstate for every block passed, with no variants, facing, etc. As my custom method [`registerModModelTexturePool()`](https://github.com/Fellteros/vanillablocksplus/blob/b46b5040de7f69abe5e64c1f6964cefc59f91b21/src/main/java/net/fellter/vanillablocksplus/util/ModBlockStateModelGenerator.java#L113) doesn't do that (so the original look is used), I'll change it and release the fix ASAP. Then it should work as intended.
Thanks
