### ISSUE TITLE
2.1.2 is mistakenly labelled as being for 1.21-1.21.3 on Modrinth

### ISSUE THREAD

**Issue by Poopooracoocoo** [Fellteros/vanillablocksplus-1.20.1#5]
https://modrinth.com/mod/vanilla+-blocks/version/2.1.2

It should be 1.21.2-1.21.3

When you load 2.1.2 on MC 1.21.1, you see the following crash on launch:
[crash-2024-12-06_16.26.55-client.txt](https://github.com/user-attachments/files/18033164/crash-2024-12-06_16.26.55-client.txt)
[latest.log](https://github.com/user-attachments/files/18033165/latest.log)

**Comment by Fellteros** [comment]
Thanks, fixed it.

**Comment by Poopooracoocoo** [comment]
Please add 1.21.2.

**Comment by Fellteros** [comment]
Sorry forgot about it, should be all good now
